// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfMULhNC9UnFRBG3oFP3UznA5UULqEANM',
    appId: '1:915308354729:web:d2cd2cc1ec5077248f9db8',
    messagingSenderId: '915308354729',
    projectId: 'notes2-9c5f7',
    authDomain: 'notes2-9c5f7.firebaseapp.com',
    storageBucket: 'notes2-9c5f7.appspot.com',
    measurementId: 'G-1W3BVDN8VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjDK8OjrD3yDqLVab8lsQqRrL12jFSDI0',
    appId: '1:915308354729:android:5f58a95fdb23c0c88f9db8',
    messagingSenderId: '915308354729',
    projectId: 'notes2-9c5f7',
    storageBucket: 'notes2-9c5f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlBG0o3qwSZBLIpjczS6488RpaWHcn1g',
    appId: '1:915308354729:ios:d612cd5bc30c8b068f9db8',
    messagingSenderId: '915308354729',
    projectId: 'notes2-9c5f7',
    storageBucket: 'notes2-9c5f7.appspot.com',
    iosClientId: '915308354729-ljm9kg9bgrmh2ik2naodmn9649ckikcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.note3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnlBG0o3qwSZBLIpjczS6488RpaWHcn1g',
    appId: '1:915308354729:ios:d612cd5bc30c8b068f9db8',
    messagingSenderId: '915308354729',
    projectId: 'notes2-9c5f7',
    storageBucket: 'notes2-9c5f7.appspot.com',
    iosClientId: '915308354729-ljm9kg9bgrmh2ik2naodmn9649ckikcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.note3',
  );
}
